import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('glp_lang') || 'hi';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('glp_lang', lang);
  };

  const t = (key) => {
    const translations = {
      en: {
        // Navbar
        home: 'Home',
        details: 'Details',
        quizzes: 'Quizzes',
        contact: 'Contact',
        login: 'Login',
        logout: 'Logout',
        dashboard: 'Dashboard',
        startLearning: 'Start Learning',
        
        // Footer
        footerDesc: "Rural India's leading gamified learning platform. We make education engaging, multilingual, and rewarding for every village.",
        quickLinks: 'Quick Links',
        socialNgo: 'Social & NGO',
        aboutUs: 'About Us',
        contactUs: 'Contact Us',
        ngoPartners: 'NGO Partners',
        volunteer: 'Volunteer',
        contributeQuiz: 'Contribute Quiz',
        rightsReserved: 'All rights reserved.',
        explore: 'Explore',
        learning: 'Learning',
        subjects: 'Subjects',
        games: 'Games',

        // Landing Page - Hero
        heroBadge: '🌱 Rural Education Revolution',
        heroH1_1: 'Play, Learn &',
        heroH1_2: 'Win!',
        heroP: 'Gamified learning platform designed for rural India — quizzes, mini games, rewards & leaderboards in Hindi and regional languages.',
        startLearningFree: 'Start Learning Free',
        loginArrow: 'Login →',
        heroStudentsBadge: '5,000+ Students Learning',

        // Landing Page - Stats
        students: 'Students',
        quizzesStat: 'Quizzes',
        villages: 'Villages',
        languages: 'Languages',

        // Landing Page - Features
        platformFeatures: 'Platform Features',
        featuresTitle: 'A New Way for\nEvery Child',
        featuresSub: 'Everything a rural student needs — fun, engaging, and in their own language.',
        featureSmartQuizzesTitle: 'Smart Quizzes',
        featureSmartQuizzesDesc: 'Subject-wise quizzes in Hindi & regional languages, tailored for NCERT curriculum from Class 1–10.',
        featureMiniGamesTitle: 'Mini Games',
        featureMiniGamesDesc: 'Learn through interactive games — spell words, solve maths puzzles, and explore science visually.',
        featureLeaderboardsTitle: 'Leaderboards',
        featureLeaderboardsDesc: 'Village-level, district-level, and national leaderboards to spark friendly competition.',
        featureEarnRewardsTitle: 'Earn Rewards',
        featureEarnRewardsDesc: 'Collect coins, badges and certificates. Redeem rewards for school supplies and more.',
        featureMultilanguageTitle: 'Multi-language',
        featureMultilanguageDesc: 'Full support in Hindi, Bhojpuri, Marathi, Tamil, and Telugu — more being added.',
        featureOfflineTitle: 'Offline Mode',
        featureOfflineDesc: 'Works without internet — download content at school and study anywhere, anytime.',

        // Landing Page - How it works
        howItWorks: 'How It Works',
        howTitle: '4 Simple Steps\nto Start Learning',
        howSub: 'Register once, and your child is on their way to becoming a champion learner.',
        step1Title: 'Register',
        step1Desc: 'Free registration with just a phone number — no email or credit card needed.',
        step2Title: 'Choose Your Class',
        step2Desc: 'Classes 1 to 10 — study material in your preferred board and language.',
        step3Title: 'Play & Learn',
        step3Desc: 'Complete daily quizzes, games, and challenges to earn points.',
        step4Title: 'Get Rewards',
        step4Desc: 'Top learners get certificates, badges, and useful school supplies.',

        // Landing Page - Testimonials
        realStories: 'Real Stories',
        familiesSay: 'What Families Say',
        testi1Name: 'Priya Sharma',
        testi1Village: 'Gorakhpur, UP',
        testi1Text: 'My son improved his math score by 40% in 3 months. This platform really works!',
        testi2Name: 'Ramesh Yadav',
        testi2Village: 'Nashik, Maharashtra',
        testi2Text: 'We do not have steady internet in the village, but with offline mode, children study daily. Very good.',
        testi3Name: 'Savitri Devi',
        testi3Village: 'Patna, Bihar',
        testi3Text: 'Everything is available in Hindi, so my daughter studies by herself. Thank you!',
        testi4Name: 'Sunita Devi',
        testi4Village: 'Mathura, UP',
        testi4Text: 'My children play quizzes daily now. Their maths has improved so much because of this platform!',

        // Landing Page - CTA
        ctaTitle: 'Start Today — Completely Free!',
        ctaSub: '10,000+ students already learning. Join them and transform your child\'s future with fun, gamified education.',
        ctaBtnPrimary: 'Register Now — It\'s Free',
        ctaBtnSecondary: 'Already have an account?',

        // About Page - Hero
        aboutEyebrow: 'About VidyaKhel',
        aboutHeroTitle: 'Empowering Rural India\nThrough Play',
        aboutHeroSub: 'We believe every child deserves access to quality, engaging education — regardless of where they live.',
        
        // About Page - Our Story
        aboutStoryEyebrow: 'Our Story',
        aboutStoryTitle: 'Why We Started',
        aboutStoryP1: 'In 2024, a group of passionate developers and educators visited rural schools across Uttar Pradesh. What they found was heartbreaking — bright, curious children with no access to engaging learning tools.',
        aboutStoryP2: 'Traditional textbooks couldn\'t hold their attention. Internet was unreliable. And most digital platforms were in English only. That\'s when VidyaKhel was born — a platform built from the ground up for rural India.',
        
        // About Page - Mission
        aboutMissionEyebrow: 'Our Mission',
        aboutMissionTitle: 'What We Aim To Do',
        aboutMissionP1: 'Make quality education accessible, engaging, and fun for every child in rural India through gamification and local languages.',
        aboutMissionP2: 'We aim to reduce dropout rates, improve learning outcomes, and spark a lifelong love for education in communities that need it most.',
        
        // About Page - Vision
        aboutVisionEyebrow: 'Our Vision',
        aboutVisionTitle2: 'Building The Future',
        aboutVisionP1: 'A world where no child is left behind due to geography, language, or economic status.',
        aboutVisionP2: 'By 2030, we envision VidyaKhel reaching 1 million+ students across 10,000+ villages, available in 15+ Indian languages.',
        
        // About Page - What We Offer
        aboutOfferEyebrow: 'What We Offer',
        aboutOfferTitle: 'Everything A Student Needs',
        aboutOffer1Title: 'Smart Quizzes',
        aboutOffer1Desc: 'Subject-wise quizzes tailored for NCERT curriculum, available in Hindi and regional languages.',
        aboutOffer2Title: 'Mini Games',
        aboutOffer2Desc: 'Interactive games that make learning math, science, and language fun and engaging.',
        aboutOffer3Title: 'Rewards & Badges',
        aboutOffer3Desc: 'Earn XP, coins, and certificates. Redeem rewards for school supplies.',
        aboutOffer4Title: 'Leaderboards',
        aboutOffer4Desc: 'Village, district, and national level leaderboards to inspire healthy competition.',
        aboutOffer5Title: 'Offline Mode',
        aboutOffer5Desc: 'Download content at school, study anywhere without internet connectivity.',
        aboutOffer6Title: 'Multi-Language',
        aboutOffer6Desc: 'Full support in Hindi, Bhojpuri, Marathi, Tamil, Telugu and more being added.',
        
        // About Page - Why Choose Us
        aboutWhyEyebrow: 'Why Choose Us',
        aboutWhyTitle: 'What Makes Us Different',
        aboutWhy1Title: 'Built For Rural India',
        aboutWhy1Desc: 'Designed specifically for low-bandwidth, offline-first environments with local language support.',
        aboutWhy2Title: '100% Free Forever',
        aboutWhy2Desc: 'No hidden charges, no premium plans. Every feature is free for every student.',
        aboutWhy3Title: 'Teacher Approved',
        aboutWhy3Desc: 'Content aligned with NCERT syllabus, reviewed by experienced rural educators.',
        aboutWhy4Title: 'Community Driven',
        aboutWhy4Desc: 'Built with feedback from 500+ families across 120 villages in 5 states.',
        
        // About Page - Our Values
        aboutValuesEyebrow: 'Our Values',
        aboutValuesTitle: 'What We Stand For',
        aboutValue1Title: 'Innovation',
        aboutValue1Desc: 'Constantly evolving our platform with the latest in EdTech and gamification.',
        aboutValue2Title: 'Inclusivity',
        aboutValue2Desc: 'Education for every child — regardless of caste, gender, language, or location.',
        aboutValue3Title: 'Growth',
        aboutValue3Desc: 'Nurturing curiosity and empowering every learner to reach their full potential.',
        aboutValue4Title: 'Community',
        aboutValue4Desc: 'Working hand-in-hand with villages, teachers, and NGOs to create lasting impact.',
        
        // About Page - CTA
        aboutCtaTitle: 'Start Your Learning Journey Today',
        aboutCtaSub: 'Join 5,000+ students already learning on VidyaKhel. It\'s completely free!',
        aboutCtaBtn: 'Get Started Free',
        aboutCtaLogin: 'Already have an account?',

        // Contact Page
        getInTouch: '📬 Get in Touch',
        contactUsTitle: 'Contact Us & Support',
        contactUsSub: 'Have any suggestions, questions, or want to contribute quizzes? Reach out to us!',
        villageOffice: '📍 Village Office',
        villageOfficeDesc: 'VidyaKhel Foundation,\nCommunity Center, Rampur Village,\nLucknow, Uttar Pradesh, India',
        emailSupport: '📧 Email Support',
        fullName: 'Full Name',
        fullNamePlace: 'Your Name',
        emailAddr: 'Email Address',
        iamA: 'I am a...',
        roleStudent: 'Student / Student Parent',
        roleTeacher: 'Teacher / Educator',
        roleVolunteer: 'Volunteer / NGO Representative',
        roleOther: 'Other',
        messageSuggestion: 'Message / Suggestion',
        messagePlace: 'How can we help you or improve the site?',
        sendMessage: '📨 Send Message',
        sending: 'Sending...',

        // Login & Register Pages
        backToHome: '← Back to Home',
        welcomeBack: 'Welcome Back!',
        signInContinue: 'Sign in to continue your learning journey',
        password: 'Password',
        forgotPasswordQ: 'Forgot Password?',
        signIn: 'Sign In',
        signingIn: 'Signing in…',
        dontHaveAccount: "Don't have an account?",
        registerHere: 'Register here →',
        alreadyHaveAccount: 'Already have an account?',
        signInArrow: 'Sign in →',
        joinVidyaKhel: 'Join VidyaKhel',
        startFreeJourney: 'Start your free learning journey today!',
        createAccount: 'Create Account',
        fillDetails: 'Fill in your details to get started',
        fullNameLabel: 'Full Name *',
        emailAddrPlace: 'your@email.com',
        passwordPlace: 'Min 6 characters',
        classGrade: 'Class / Grade *',
        selectGrade: 'Select Grade',
        classOptionText: 'Class {grade}',
        villageOpt: 'Village (optional)',
        villagePlace: 'Village name',
        districtOpt: 'District (optional)',
        districtPlace: 'District',
        createFreeAccount: 'Create Free Account',
        creatingAccount: 'Creating Account…',
        regFeature1: 'Fun Quizzes & Games',
        regFeature2: 'Earn XP & Badges',
        regFeature3: 'Track Your Progress',
        regFeature4: '100% Free Forever',

        // Forgot Password Page
        dontWorry: "Don't Worry!",
        dontWorryDesc: "It happens to everyone. We'll send you a link to reset your password right away.",
        checkInbox: 'Check your email inbox',
        clickResetLink: 'Click the reset link',
        setNewPassword: 'Set a new password',
        enterLinkedEmail: "Enter the email address linked to your account. We'll send you a secure reset link.",
        sendResetLink: 'Send Reset Link',
        sendingLink: 'Sending...',
        emailSent: 'Email Sent!',
        emailSentDesc: "We've sent a password reset link to {email}. Please check your inbox (and spam folder, just in case).",
        linkExpiresWarning: 'The link will expire in 15 minutes. If you don\'t see it, check your spam folder.',
        tryDifferentEmail: '← Try a different email',
        backToLogin: '← Back to Login',

        // Dashboard & Sidebar Link Layout
        dashboardLink: 'Dashboard',
        subjectsLink: 'Subjects',
        gamesLink: 'Games',
        leaderboardLink: 'Leaderboard',
        rewardsLink: 'Rewards',
        profileLink: 'Profile',
        backToHomeLink: 'Back to Home',
        teacherPanelLink: 'Teacher Panel',
        createQuizLink: 'Create Quiz',
        areYouSureLogout: 'Are you sure?',
        logoutConfirmDesc: 'Do you really want to logout from VidyaKhel?',
        cancel: 'Cancel',
        yesLogout: 'Yes, Logout',

        // Student Dashboard
        levelNovice: 'Novice',
        levelExplorer: 'Explorer',
        levelAchiever: 'Achiever',
        levelChampion: 'Champion',
        loadingDashboard: 'Loading Dashboard...',
        welcomeUser: 'Welcome, {name}!',
        classStudent: 'Class {grade} Student',
        chooseLearningLevel: 'Choose Learning Level',
        learningLevelDesc: 'Select a class level to view topics. Accessing outside your enrolled group activates Practice Mode.',
        groupA: 'Group A',
        groupB: 'Group B',
        groupC: 'Group C',
        classes1_3: 'Class 1–3',
        classes4_6: 'Class 4–6',
        classes7_10: 'Class 7–10',
        myClass: 'My Class',
        practiceModeActive: 'Practice Mode Active!',
        practiceModeActiveDesc: 'Points and XP will not be added to your profile.',
        totalPoints: 'Total Points',
        levelStatus: 'Level Status',
        badgesEarned: 'Badges Earned',
        dayStreak: 'Day Streak',
        currentLevel: 'Current Level',
        totalXp: 'Total XP',
        xpToNextLevel: '{xp} XP to next level',
        quickActions: 'Quick Actions',
        recentActivity: 'Recent Activity',

        // Subjects Page
        subjectsTitle: 'Subjects',
        subjectsSubtitle: 'Choose a subject to start your learning journey and earn XP!',
        startLearningBtn: 'Start Learning',
        normalMode: 'Normal Mode:',
        normalModeDesc: 'Complete this quiz to earn up to {xp} XP!',
        practiceMode: 'Practice Mode Active (0 XP)',
        practiceModeDesc: "You're exploring a different class level. No XP will be awarded.",
        totalQuestions: 'Total Questions:',
        questionsCount: '{count} Questions',
        timeLimit: 'Time Limit:',
        timeLimitMins: '{count} Minutes',
        reviewPrevQ: 'You can review previous questions during the quiz.',
        startQuizBtn: 'Start Quiz',

        // Games Page
        gamesTitle: 'Games',
        gamesSubtitle: 'Play fun games, earn XP points and level up your skills!',
        playNowBtn: 'Play Now',
        chooseDifficulty: 'Choose Difficulty',
        xpRewardOnCompletion: 'XP Reward: +{xp} XP on completion',
        questionsMathProblems: 'Questions: {count} math problems',
        timePerQuestionSecs: 'Time per Question: {count} seconds',
        pairsCardsCount: 'Pairs: {pairs} pairs ({cards} cards)',
        gameHintFooter: 'Answer correctly to earn maximum points. Have fun!',
        startGameBtn: 'Start Game',

        // Rewards Page
        rewardsTitle: 'Rewards & Badges',
        rewardsSubtitle: 'Earn badges by collecting XP points and completing challenges!',
        currentXpLabel: 'Your Current XP',
        earnedBadgeText: 'Earned!',
        claimBtn: 'Claim',
        xpMoreBadge: '{xp} XP more',
        noRewardsAvailable: 'No rewards available yet. Check back soon!',

        // Profile Page
        myProfileTitle: 'My Profile',
        myProfileSubtitle: 'Update your information and avatar',
        chooseAvatar: 'Choose Avatar',
        myBadges: 'My Badges',
        saveChanges: 'Save Changes',
        savingChanges: 'Saving...',

        // Quiz Result & Done Pages
        perfectScore: 'Perfect Score! Awesome!',
        excellentScore: 'Excellent! Well Done!',
        goodJob: 'Good Job!',
        keepPracticing: 'Keep Practicing!',
        keepLearning: 'Keep Learning!',
        correct: 'Correct',
        wrong: 'Wrong',
        backToSubjects: 'Back to Subjects',
        practiceModeCompleted: 'Practice Mode Completed:',
        practiceModeCompletedDesc: 'This quiz belongs to a class group outside your enrolled group. To earn points (XP) and unlock rewards, choose a quiz in your enrolled class level.',

        // Game Names
        wordPuzzleName: 'Word Puzzle Challenge',
        wordPuzzleDesc: 'Unscramble words, build vocabulary, boost XP by 2x.',
        mathSprintName: 'Math Sprint',
        mathSprintDesc: 'Solve rapid-fire math problems and boost XP by 7x.',
        mathChallengeName: 'Math Challenge',
        mathChallengeDesc: 'Solve math equations as fast as you can! Beat the clock and earn points for every correct answer.',
        memoryMatchName: 'Memory Match',
        memoryMatchDesc: 'Flip cards to find matching pairs! Train your memory and concentration skills.',
        mathChallengeSub: 'Mathematics',
        memoryMatchSub: 'Brain & Logic',

        // Memory Match Cards
        mmCat: 'Cat',
        mmDog: 'Dog',
        mmSun: 'Sun',
        mmMoon: 'Moon',
        mmStar: 'Star',
        mmHeart: 'Heart',
        mmTree: 'Tree',
        mmApple: 'Apple',
        mmFire: 'Fire',
        mmWater: 'Water',
        mmThunder: 'Thunder',
        mmGem: 'Gem',
        mmRocket: 'Rocket',
        mmCrown: 'Crown',
        mmFlower: 'Flower',
        mmPlanet: 'Planet',

        // Quiz Play UI
        solveThis: 'Solve this',
        mathChallengeTitle: 'Math Challenge',
        memoryMatchTitle: 'Memory Match',
        movesLabel: 'MOVES',
        timeLabel: 'TIME',
        flipMatchHint: 'Flip cards to find matching pairs. Fewer moves = more XP!',
        perfectMemory: 'Perfect Memory!',
        wellDone: 'Well Done!',
        youDidIt: 'You Did It!',
        movesUsed: 'Moves Used',
        timeTaken: 'Time Taken',
        backToGames: 'Back to Games',
        questionTextPlay: 'Question {num} of {total}',
        quizTopic: 'Topic',
        quizQuiz: 'Quiz'
      },
      hi: {
        // Navbar
        home: 'होम',
        details: 'डिटेल्स',
        quizzes: 'क्विज़',
        contact: 'संपर्क',
        login: 'लॉगिन',
        logout: 'लॉगआऊट',
        dashboard: 'डैशबोर्ड',
        startLearning: 'पढ़ना शुरू करें',
        
        // Footer
        footerDesc: "ग्रामीण भारत का अग्रणी गेमीफाइड लर्निंग प्लेटफॉर्म। हम हर गांव के लिए शिक्षा को आकर्षक, बहुभाषी और पुरस्कृत बनाते हैं।",
        quickLinks: 'त्वरित लिंक',
        socialNgo: 'सामाजिक और एनजीओ',
        aboutUs: 'हमारे बारे में',
        contactUs: 'संपर्क करें',
        ngoPartners: 'एनजीओ पार्टनर्स',
        volunteer: 'स्वयंसेवक',
        contributeQuiz: 'क्विज़ योगदान करें',
        rightsReserved: 'सर्वाधिकार सुरक्षित।',
        explore: 'खोजें',
        learning: 'सीखना',
        subjects: 'विषय',
        games: 'खेल',

        // Landing Page - Hero
        heroBadge: '🌱 ग्रामीण शिक्षा क्रांति',
        heroH1_1: 'खेलो, सीखो और',
        heroH1_2: 'जीतो!',
        heroP: 'ग्रामीण भारत के लिए डिज़ाइन किया गया गेमीफाइड लर्निंग प्लेटफॉर्म — हिंदी और क्षेत्रीय भाषाओं में क्विज़, मिनी गेम्स, रिवॉर्ड्स और लीडरबोर्ड।',
        startLearningFree: 'मुफ़्त में पढ़ना शुरू करें',
        loginArrow: 'लॉगिन करें →',
        heroStudentsBadge: '5,000+ छात्र सीख रहे हैं',

        // Landing Page - Stats
        students: 'छात्र',
        quizzesStat: 'क्विज़',
        villages: 'गाँव',
        languages: 'भाषाएं',

        // Landing Page - Features
        platformFeatures: 'प्लेटफॉर्म की विशेषताएं',
        featuresTitle: 'हर बच्चे के लिए\nएक नया तरीका',
        featuresSub: 'ग्रामीण छात्र की ज़रूरत की हर चीज़ — मज़ेदार, आकर्षक और उनकी अपनी भाषा में।',
        featureSmartQuizzesTitle: 'स्मार्ट क्विज़',
        featureSmartQuizzesDesc: 'कक्षा 1 से 10 तक के एनसीईआरटी पाठ्यक्रम के लिए तैयार किए गए हिंदी और क्षेत्रीय भाषाओं में विषय-वार क्विज़।',
        featureMiniGamesTitle: 'मिनी गेम्स',
        featureMiniGamesDesc: 'इंटरैक्टिव खेलों के माध्यम से सीखें — शब्दों की वर्तनी, गणित की पहेलियाँ हल करें, और विज्ञान को स्पष्ट रूप से समझें।',
        featureLeaderboardsTitle: 'लीडरबोर्ड',
        featureLeaderboardsDesc: 'दोस्ताना प्रतिस्पर्धा शुरू करने के लिए ग्राम-स्तरीय, जिला-स्तरीय और राष्ट्रीय लीडरबोर्ड।',
        featureEarnRewardsTitle: 'पुरस्कार कमाएं',
        featureEarnRewardsDesc: 'सिक्के, बैज और प्रमाणपत्र एकत्र करें। स्कूल की आपूर्ति और अन्य चीज़ों के लिए पुरस्कार भुनाएं।',
        featureMultilanguageTitle: 'बहुभाषी सहायता',
        featureMultilanguageDesc: 'हिंदी, भोजपुरी, मराठी, तमिल और तेलुगु में पूर्ण समर्थन — और भी भाषाएं जोड़ी जा रही हैं।',
        featureOfflineTitle: 'ऑफ़लाइन मोड',
        featureOfflineDesc: 'बिना इंटरनेट के काम करता है — स्कूल में सामग्री डाउनलोड करें और कभी भी, कहीं भी पढ़ें।',

        // Landing Page - How it works
        howItWorks: 'यह कैसे काम करता है',
        howTitle: 'पढ़ना शुरू करने के लिए\n4 आसान चरण',
        howSub: 'एक बार पंजीकरण करें, और आपका बच्चा चैंपियन शिक्षार्थी बनने की राह पर है।',
        step1Title: 'पंजीकरण करें',
        step1Desc: 'फ़ोन नंबर से मुफ़्त पंजीकरण — कोई ईमेल या क्रेडिट कार्ड की आवश्यकता नहीं है।',
        step2Title: 'अपनी कक्षा चुनें',
        step2Desc: 'कक्षा 1 से 10 तक — अपने बोर्ड और पसंदीदा भाषा में अध्ययन सामग्री।',
        step3Title: 'खेलें और सीखें',
        step3Desc: 'दैनिक क्विज़, खेल और चुनौतियाँ पूरी करें और अंक कमाएँ।',
        step4Title: 'पुरस्कार पाएं',
        step4Desc: 'शीर्ष शिक्षार्थियों को प्रमाणपत्र, बैज और स्कूल की आपूर्ति मिलती है।',

        // Landing Page - Testimonials
        realStories: 'सच्ची कहानियाँ',
        familiesSay: 'परिवार क्या कह रहे हैं',
        testi1Name: 'प्रिया शर्मा',
        testi1Village: 'गोरखपुर, उत्तर प्रदेश',
        testi1Text: 'मेरे बेटे ने 3 महीने में गणित में 40% सुधार किया। यह प्लेटफॉर्म वास्तव में काम करता है!',
        testi2Name: 'रमेश यादव',
        testi2Village: 'नासिक, महाराष्ट्र',
        testi2Text: 'गाँव में इंटरनेट नहीं होता पर ऑफ़लाइन मोड से बच्चे रोज़ पढ़ते हैं। बहुत अच्छा है।',
        testi3Name: 'सावित्री देवी',
        testi3Village: 'पटना, बिहार',
        testi3Text: 'हिंदी में सब कुछ मिलता है तो मेरी बेटी खुद से पढ़ लेती है। शुक्रिया!',
        testi4Name: 'सुनीता देवी',
        testi4Village: 'मथुरा, उत्तर प्रदेश',
        testi4Text: 'मेरे बच्चे अब रोज़ क्विज़ खेलते हैं। उनका गणित इस प्लेटफॉर्म की वजह से बहुत सुधर गया है!',

        // Landing Page - CTA
        ctaTitle: 'आज ही शुरू करें — बिल्कुल मुफ्त!',
        ctaSub: '10,000+ छात्र पहले से ही सीख रहे हैं। उनके साथ जुड़ें और मज़ेदार, गेमीफाइड शिक्षा के साथ अपने बच्चे के भविष्य को बदलें।',
        ctaBtnPrimary: 'अभी पंजीकरण करें — यह मुफ़्त है',
        ctaBtnSecondary: 'पहले से ही एक खाता है?',

        // About Page - Hero
        aboutEyebrow: 'विद्याखेल के बारे में',
        aboutHeroTitle: 'खेल के माध्यम से\nग्रामीण भारत को सशक्त बनाना',
        aboutHeroSub: 'हम मानते हैं कि हर बच्चे को गुणवत्तापूर्ण, आकर्षक शिक्षा तक पहुँच मिलनी चाहिए — चाहे वो कहीं भी रहता हो।',
        
        // About Page - Our Story
        aboutStoryEyebrow: 'हमारी कहानी',
        aboutStoryTitle: 'हमने क्यों शुरू किया',
        aboutStoryP1: '2024 में, डेवलपर्स और शिक्षकों के एक समूह ने उत्तर प्रदेश के ग्रामीण स्कूलों का दौरा किया। जो उन्होंने देखा वो दिल दहला देने वाला था — होशियार, जिज्ञासु बच्चे जिनके पास कोई आकर्षक शिक्षण उपकरण नहीं था।',
        aboutStoryP2: 'पारंपरिक किताबें उनका ध्यान नहीं रख पाती थीं। इंटरनेट अनिश्चित था। और अधिकांश डिजिटल प्लेटफॉर्म केवल अंग्रेजी में थे। तभी विद्याखेल का जन्म हुआ — ग्रामीण भारत के लिए खासतौर पर बनाया गया प्लेटफॉर्म।',
        
        // About Page - Mission
        aboutMissionEyebrow: 'हमारा मिशन',
        aboutMissionTitle: 'हम क्या करना चाहते हैं',
        aboutMissionP1: 'गेमीफिकेशन और स्थानीय भाषाओं के माध्यम से ग्रामीण भारत के हर बच्चे के लिए गुणवत्तापूर्ण शिक्षा को सुलभ, आकर्षक और मज़ेदार बनाना।',
        aboutMissionP2: 'हमारा लक्ष्य ड्रॉपआउट दर को कम करना, सीखने के परिणामों में सुधार करना और उन समुदायों में शिक्षा के प्रति आजीवन प्रेम जगाना है जिन्हें इसकी सबसे ज़्यादा ज़रूरत है।',
        
        // About Page - Vision
        aboutVisionEyebrow: 'हमारा विज़न',
        aboutVisionTitle2: 'भविष्य का निर्माण',
        aboutVisionP1: 'एक ऐसी दुनिया जहाँ भूगोल, भाषा या आर्थिक स्थिति की वजह से कोई भी बच्चा पीछे न छूटे।',
        aboutVisionP2: '2030 तक, हम विद्याखेल को 10,000+ गांवों में 10 लाख+ छात्रों तक पहुंचाने की कल्पना करते हैं, 15+ भारतीय भाषाओं में उपलब्ध।',
        
        // About Page - What We Offer
        aboutOfferEyebrow: 'हम क्या देते हैं',
        aboutOfferTitle: 'छात्र को जो चाहिए सब कुछ',
        aboutOffer1Title: 'स्मार्ट क्विज़',
        aboutOffer1Desc: 'NCERT पाठ्यक्रम के अनुसार विषय-वार क्विज़, हिंदी और क्षेत्रीय भाषाओं में उपलब्ध।',
        aboutOffer2Title: 'मिनी गेम्स',
        aboutOffer2Desc: 'इंटरैक्टिव खेल जो गणित, विज्ञान और भाषा सीखना मज़ेदार और आकर्षक बनाते हैं।',
        aboutOffer3Title: 'पुरस्कार और बैज',
        aboutOffer3Desc: 'XP, सिक्के और प्रमाणपत्र कमाएं। स्कूल की सामग्री के लिए पुरस्कार भुनाएं।',
        aboutOffer4Title: 'लीडरबोर्ड',
        aboutOffer4Desc: 'स्वस्थ प्रतिस्पर्धा को प्रेरित करने के लिए गांव, जिला और राष्ट्रीय स्तर के लीडरबोर्ड।',
        aboutOffer5Title: 'ऑफ़लाइन मोड',
        aboutOffer5Desc: 'स्कूल में कंटेंट डाउनलोड करें, बिना इंटरनेट के कहीं भी पढ़ें।',
        aboutOffer6Title: 'बहुभाषी',
        aboutOffer6Desc: 'हिंदी, भोजपुरी, मराठी, तमिल, तेलुगु में पूर्ण समर्थन और अधिक भाषाएं जुड़ रही हैं।',
        
        // About Page - Why Choose Us
        aboutWhyEyebrow: 'हमें क्यों चुनें',
        aboutWhyTitle: 'हम कैसे अलग हैं',
        aboutWhy1Title: 'ग्रामीण भारत के लिए बना',
        aboutWhy1Desc: 'कम बैंडविड्थ, ऑफ़लाइन-फर्स्ट वातावरण और स्थानीय भाषा समर्थन के लिए विशेष रूप से डिज़ाइन किया गया।',
        aboutWhy2Title: '100% हमेशा मुफ्त',
        aboutWhy2Desc: 'कोई छिपे हुए शुल्क नहीं, कोई प्रीमियम प्लान नहीं। हर सुविधा हर छात्र के लिए मुफ्त है।',
        aboutWhy3Title: 'शिक्षक स्वीकृत',
        aboutWhy3Desc: 'NCERT पाठ्यक्रम से जुड़ी सामग्री, अनुभवी ग्रामीण शिक्षकों द्वारा समीक्षित।',
        aboutWhy4Title: 'समुदाय संचालित',
        aboutWhy4Desc: '5 राज्यों के 120 गांवों में 500+ परिवारों की प्रतिक्रिया से निर्मित।',
        
        // About Page - Our Values
        aboutValuesEyebrow: 'हमारे मूल्य',
        aboutValuesTitle: 'हम किसके लिए खड़े हैं',
        aboutValue1Title: 'नवाचार',
        aboutValue1Desc: 'EdTech और गेमीफिकेशन में नवीनतम के साथ हमारे प्लेटफॉर्म को लगातार विकसित करना।',
        aboutValue2Title: 'समावेशिता',
        aboutValue2Desc: 'हर बच्चे के लिए शिक्षा — जाति, लिंग, भाषा या स्थान की परवाह किए बिना।',
        aboutValue3Title: 'विकास',
        aboutValue3Desc: 'जिज्ञासा को पोषित करना और हर शिक्षार्थी को अपनी पूरी क्षमता तक पहुंचने के लिए सशक्त बनाना।',
        aboutValue4Title: 'समुदाय',
        aboutValue4Desc: 'स्थायी प्रभाव बनाने के लिए गांवों, शिक्षकों और NGO के साथ मिलकर काम करना।',
        
        // About Page - CTA
        aboutCtaTitle: 'आज ही अपनी सीखने की यात्रा शुरू करें',
        aboutCtaSub: 'विद्याखेल पर पहले से 5,000+ छात्र सीख रहे हैं। यह पूरी तरह मुफ्त है!',
        aboutCtaBtn: 'मुफ्त शुरू करें',
        aboutCtaLogin: 'पहले से खाता है?',

        // Contact Page
        getInTouch: '📬 संपर्क में रहें',
        contactUsTitle: 'हमसे संपर्क करें और सहायता',
        contactUsSub: 'कोई सुझाव, प्रश्न हैं, या क्विज़ में योगदान देना चाहते हैं? हमसे संपर्क करें!',
        villageOffice: '📍 ग्राम कार्यालय',
        villageOfficeDesc: 'विद्याखेल फाउंडेशन,\nसामुदायिक केंद्र, रामपुर गांव,\nलखनऊ, उत्तर प्रदेश, भारत',
        emailSupport: '📧 ईमेल सहायता',
        fullName: 'पूरा नाम',
        fullNamePlace: 'आपका नाम',
        emailAddr: 'ईमेल पता',
        iamA: 'मैं हूँ...',
        roleStudent: 'छात्र / छात्र के माता-पिता',
        roleTeacher: 'शिक्षक / शिक्षक',
        roleVolunteer: 'स्वयंसेवक / गैर सरकारी संगठन के प्रतिनिधि',
        roleOther: 'अन्य',
        messageSuggestion: 'संदेश / सुझाव',
        messagePlace: 'हम आपकी कैसे मदद कर सकते हैं या साइट में कैसे सुधार कर सकते हैं?',
        sendMessage: '📨 संदेश भेजें',
        sending: 'भेज रहा है...',

        // Login & Register Pages
        backToHome: '← होम पर वापस जाएँ',
        welcomeBack: 'आपका स्वागत है!',
        signInContinue: 'अध्ययन जारी रखने के लिए साइन इन करें',
        password: 'पासवर्ड',
        forgotPasswordQ: 'पासवर्ड भूल गए?',
        signIn: 'साइन इन करें',
        signingIn: 'साइन इन हो रहा है…',
        dontHaveAccount: 'खाता नहीं है?',
        registerHere: 'यहाँ पंजीकरण करें →',
        alreadyHaveAccount: 'पहले से ही एक खाता है?',
        signInArrow: 'साइन इन करें →',
        joinVidyaKhel: 'विद्याखेल से जुड़ें',
        startFreeJourney: 'आज ही अपनी मुफ्त सीखने की यात्रा शुरू करें!',
        createAccount: 'खाता बनाएं',
        fillDetails: 'शुरू करने के लिए अपनी जानकारी भरें',
        fullNameLabel: 'पूरा नाम *',
        emailAddrPlace: 'your@email.com',
        passwordPlace: 'न्यूनतम 6 अक्षर',
        classGrade: 'कक्षा / ग्रेड *',
        selectGrade: 'कक्षा चुनें',
        classOptionText: 'कक्षा {grade}',
        villageOpt: 'गाँव (वैकल्पिक)',
        villagePlace: 'गाँव का नाम',
        districtOpt: 'जिला (वैकल्पिक)',
        districtPlace: 'जिला',
        createFreeAccount: 'मुफ़्त खाता बनाएं',
        creatingAccount: 'खाता बनाया जा रहा है…',
        regFeature1: 'मज़ेदार क्विज़ और खेल',
        regFeature2: 'XP और बैज कमाएं',
        regFeature3: 'अपनी प्रगति ट्रैक करें',
        regFeature4: 'हमेशा 100% मुफ्त',

        // Forgot Password Page
        dontWorry: 'चिंता न करें!',
        dontWorryDesc: 'ऐसा हर किसी के साथ होता है। हम आपको तुरंत पासवर्ड रीसेट करने के लिए एक लिंक भेजेंगे।',
        checkInbox: 'अपना ईमेल इनबॉक्स देखें',
        clickResetLink: 'रीसेट लिंक पर क्लिक करें',
        setNewPassword: 'नया पासवर्ड सेट करें',
        enterLinkedEmail: 'अपने खाते से जुड़ा ईमेल पता दर्ज करें। हम आपको एक सुरक्षित रीसेट लिंक भेजेंगे।',
        sendResetLink: 'रीसेट लिंक भेजें',
        sendingLink: 'भेजा जा रहा है...',
        emailSent: 'ईमेल भेज दिया गया!',
        emailSentDesc: "हमने {email} पर पासवर्ड रीसेट लिंक भेजा है। कृपया अपना इनबॉक्स (और स्पैम फोल्डर) जांचें।",
        linkExpiresWarning: 'लिंक 15 मिनट में समाप्त हो जाएगा। यदि आपको यह न दिखे, तो स्पैम फ़ोल्डर की जाँच करें।',
        tryDifferentEmail: '← दूसरा ईमेल आज़माएं',
        backToLogin: '← लॉगिन पर वापस जाएं',

        // Dashboard & Sidebar Link Layout
        dashboardLink: 'डैशबोर्ड',
        subjectsLink: 'विषय',
        gamesLink: 'खेल',
        leaderboardLink: 'लीडरबोर्ड',
        rewardsLink: 'पुरस्कार',
        profileLink: 'प्रोफ़ाइल',
        backToHomeLink: 'होम पर वापस जाएँ',
        teacherPanelLink: 'शिक्षक पैनल',
        createQuizLink: 'क्विज़ बनाएं',
        areYouSureLogout: 'क्या आप निश्चित हैं?',
        logoutConfirmDesc: 'क्या आप वास्तव में विद्याखेल से लॉगआउट करना चाहते हैं?',
        cancel: 'रद्द करें',
        yesLogout: 'हाँ, लॉगआउट करें',

        // Student Dashboard
        levelNovice: 'शुरुआती',
        levelExplorer: 'खोजकर्ता',
        levelAchiever: 'सफल',
        levelChampion: 'विजेता',
        loadingDashboard: 'डैशबोर्ड लोड हो रहा है...',
        welcomeUser: 'स्वागत है, {name}!',
        classStudent: 'कक्षा {grade} के छात्र',
        chooseLearningLevel: 'सीखने का स्तर चुनें',
        learningLevelDesc: 'विषय देखने के लिए कक्षा स्तर चुनें। अपने नामांकित समूह के बाहर एक्सेस करने पर अभ्यास मोड सक्रिय हो जाता है।',
        groupA: 'समूह A',
        groupB: 'समूह B',
        groupC: 'समूह C',
        classes1_3: 'कक्षा 1–3',
        classes4_6: 'कक्षा 4–6',
        classes7_10: 'कक्षा 7–10',
        myClass: 'मेरी कक्षा',
        practiceModeActive: 'अभ्यास मोड सक्रिय!',
        practiceModeActiveDesc: 'अंक और XP आपके प्रोफ़ाइल में नहीं जोड़े जाएंगे।',
        totalPoints: 'कुल अंक',
        levelStatus: 'स्तर की स्थिति',
        badgesEarned: 'अर्जित बैज',
        dayStreak: 'दिनों का सिलसिला',
        currentLevel: 'वर्तमान स्तर',
        totalXp: 'कुल XP',
        xpToNextLevel: 'अगले स्तर के लिए {xp} XP',
        quickActions: 'त्वरित कार्रवाइयां',
        recentActivity: 'हाल की गतिविधि',

        // Subjects Page
        subjectsTitle: 'विषय',
        subjectsSubtitle: 'सीखने की यात्रा शुरू करने और XP कमाने के लिए एक विषय चुनें!',
        startLearningBtn: 'सीखना शुरू करें',
        normalMode: 'सामान्य मोड:',
        normalModeDesc: 'इस क्विज़ को पूरा करके अधिकतम {xp} XP कमाएं!',
        practiceMode: 'अभ्यास मोड सक्रिय (0 XP)',
        practiceModeDesc: 'आप एक अलग कक्षा स्तर का पता लगा रहे हैं। कोई XP नहीं दिया जाएगा।',
        totalQuestions: 'कुल प्रश्न:',
        questionsCount: '{count} प्रश्न',
        timeLimit: 'समय सीमा:',
        timeLimitMins: '{count} मिनट',
        reviewPrevQ: 'आप क्विज़ के दौरान पिछले प्रश्नों की समीक्षा कर सकते हैं।',
        startQuizBtn: 'क्विज़ शुरू करें',

        // Games Page
        gamesTitle: 'खेल',
        gamesSubtitle: 'मज़ेदार खेल खेलें, XP अंक अर्जित करें और अपने कौशल को बढ़ाएं!',
        playNowBtn: 'अभी खेलें',
        chooseDifficulty: 'कठिनाई चुनें',
        xpRewardOnCompletion: 'XP पुरस्कार: पूरा होने पर +{xp} XP',
        questionsMathProblems: 'प्रश्न: {count} गणित के सवाल',
        timePerQuestionSecs: 'प्रति प्रश्न समय: {count} सेकंड',
        pairsCardsCount: 'जोड़े: {pairs} जोड़े ({cards} कार्ड)',
        gameHintFooter: 'अधिकतम अंक प्राप्त करने के लिए सही उत्तर दें। मजे करें!',
        startGameBtn: 'खेल शुरू करें',

        // Rewards Page
        rewardsTitle: 'पुरस्कार और बैज',
        rewardsSubtitle: 'XP अंक एकत्र करके और चुनौतियों को पूरा करके बैज अर्जित करें!',
        currentXpLabel: 'आपका वर्तमान XP',
        earnedBadgeText: 'अर्जित!',
        claimBtn: 'दावा करें',
        xpMoreBadge: '{xp} XP और चाहिए',
        noRewardsAvailable: 'अभी तक कोई पुरस्कार उपलब्ध नहीं है। जल्द ही वापस देखें!',

        // Profile Page
        myProfileTitle: 'मेरी प्रोफ़ाइल',
        myProfileSubtitle: 'अपनी जानकारी और अवतार अपडेट करें',
        chooseAvatar: 'अवतार चुनें',
        myBadges: 'मेरे बैज',
        saveChanges: 'परिवर्तन सहेजें',
        savingChanges: 'सहेजा जा रहा है...',

        // Quiz Result & Done Pages
        perfectScore: 'उत्कृष्ट स्कोर! बहुत बढ़िया!',
        excellentScore: 'शानदार! बहुत अच्छा किया!',
        goodJob: 'अच्छा काम किया!',
        keepPracticing: 'अभ्यास करते रहें!',
        keepLearning: 'सीखते रहें!',
        correct: 'सही',
        wrong: 'गलत',
        backToSubjects: 'विषयों पर वापस जाएं',
        practiceModeCompleted: 'अभ्यास मोड पूरा हुआ:',
        practiceModeCompletedDesc: 'यह क्विज़ आपकी कक्षा के बाहर का है। अंक (XP) कमाने और पुरस्कार अनलॉक करने के लिए, अपनी कक्षा का क्विज़ चुनें।',

        // Game Names
        wordPuzzleName: 'शब्द पहेली चैलेंज',
        wordPuzzleDesc: 'शब्दों को सुलझाएं, शब्दावली बढ़ाएं, और 2x XP पाएं।',
        mathSprintName: 'गणित स्प्रिंट',
        mathSprintDesc: 'तेज़ गणित के सवाल हल करें और 7x XP पाएं।',
        mathChallengeName: 'मैथ चैलेंज',
        mathChallengeDesc: 'जितनी जल्दी हो सके गणितीय समीकरणों को हल करें! समय से पहले सही उत्तर दें और अंक कमाएं।',
        memoryMatchName: 'मेमोरी मैच',
        memoryMatchDesc: 'Flip cards to find matching pairs! Train your memory and concentration skills.',
        mathChallengeSub: 'गणित',
        memoryMatchSub: 'मस्तिष्क और तर्क',

        // Memory Match Cards
        mmCat: 'बिल्ली',
        mmDog: 'कुत्ता',
        mmSun: 'सूरज',
        mmMoon: 'चाँद',
        mmStar: 'तारा',
        mmHeart: 'दिल',
        mmTree: 'पेड़',
        mmApple: 'सेब',
        mmFire: 'आग',
        mmWater: 'पानी',
        mmThunder: 'बिजली',
        mmGem: 'रत्न',
        mmRocket: 'रॉकेट',
        mmCrown: 'मुकुट',
        mmFlower: 'फूल',
        mmPlanet: 'ग्रह',

        // Quiz Play UI
        solveThis: 'इसे हल करें',
        mathChallengeTitle: 'मैथ चैलेंज',
        memoryMatchTitle: 'मेमोरी मैच',
        movesLabel: 'चालें',
        timeLabel: 'समय',
        flipMatchHint: 'मिलान करने वाले जोड़े खोजने के लिए कार्ड पलटें। जितनी कम चालें = उतने अधिक XP!',
        perfectMemory: 'उत्कृष्ट स्मृति!',
        wellDone: 'बहुत बढ़िया!',
        youDidIt: 'आपने कर दिखाया!',
        movesUsed: 'प्रयुक्त चालें',
        timeTaken: 'लगा समय',
        backToGames: 'खेलों पर वापस जाएं',
        questionTextPlay: 'प्रश्न {num} / {total}',
        quizTopic: 'विषय',
        quizQuiz: 'क्विज़'
      }
    };
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
